"""add constraints and ctegory_id fk

Revision ID: 83070dd5c509
Revises: 1b3d2bec8d68
Create Date: 2026-03-10 23:14:08.353617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83070dd5c509'
down_revision: Union[str, Sequence[str], None] = '1b3d2bec8d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'items', ['name'])
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'])
    op.drop_column('items', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='unique')
    op.drop_column('items', 'category_id')
    # ### end Alembic commands ###
